name: consola
description: Utilities for Dart command-line applications.
version: 0.1.0
repository: https://github.com/Tienisto/consola
topics:
  - console
  - ansi
  - cli
  - terminal

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
